<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muhammad Raisha Aulia Putranta">
<meta name="dcterms.date" content="2024-12-28">

<title>Pengaruh Ekspor Teknologi Tinggi terhadap GDP Tahun 2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Ekspor Teknologi Tinggi terhadap GDP Tahun 2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Muhammad Raisha Aulia Putranta </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 28, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
<figcaption>logo</figcaption>
</figure>
</div>
<style>
p {text-align: justify;}
</style>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Dalam era globalisasi dan perkembangan teknologi yang pesat, ekspor teknologi tinggi menjadi salah satu faktor penting dalam pertumbuhan ekonomi suatu negara. Teknologi tinggi, yang mencakup sektor seperti elektronik, bioteknologi, dan informasi, tidak hanya berkontribusi terhadap peningkatan nilai tambah produk, tetapi juga mendorong inovasi dan daya saing di pasar global.</p>
<p>Produk-produk teknologi tinggi sering kali memiliki nilai ekspor yang lebih tinggi dibandingkan dengan produk tradisional, sehingga dapat memberikan dampak signifikan terhadap Produk Domestik Bruto (GDP) suatu negara. Menurut data dari World Bank (2022), negara-negara yang mampu meningkatkan proporsi ekspor teknologi tinggi dalam total ekspor mereka cenderung mengalami pertumbuhan ekonomi yang lebih cepat.</p>
<p>Namun, hubungan antara ekspor teknologi tinggi dan GDP tidak selalu linear dan dapat dipengaruhi oleh berbagai faktor, termasuk kondisi ekonomi global, kebijakan perdagangan, dan struktur ekonomi masing-masing negara. Penelitian oleh Lee dan Malerba (2018) menunjukkan bahwa negara dengan investasi yang kuat dalam penelitian dan pengembangan (R&amp;D) serta pendidikan tinggi lebih mampu memanfaatkan potensi ekspor teknologi tinggi. Studi ini bertujuan untuk menganalisis pengaruh ekspor teknologi tinggi terhadap GDP di 135 negara pada tahun 2022. Dengan menggunakan data yang komprehensif, diharapkan penelitian ini dapat memberikan wawasan mengenai seberapa besar kontribusi ekspor teknologi tinggi terhadap pertumbuhan ekonomi dan faktor-faktor yang memengaruhi hubungan tersebut.</p>
<p>Hasil penelitian ini diharapkan dapat menjadi acuan bagi pembuat kebijakan dalam merumuskan strategi yang lebih efektif untuk meningkatkan ekspor teknologi tinggi, yang pada gilirannya dapat berkontribusi pada pertumbuhan ekonomi yang berkelanjutan. Selain itu, pemahaman yang lebih baik mengenai dinamika ini juga penting untuk negara-negara yang sedang berkembang dalam upaya mereka untuk bertransformasi menjadi ekonomi yang lebih berbasis teknologi.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini memanfaatkan data yang diperoleh melalui WDI yang diakses menggunakan perangkat lunak R. Data yang digunakan terdiri dari dua variabel utama Ekspor teknologi tinggi (High-technology exports) sebagai variabel independen (X) dan GDP (Produk Domestik Bruto) sebagai variabel dependen (Y). Data ini mencakup 135 negara yang terlibat dalam ekspor teknologi tinggi, dengan fokus pada data tahun 2022.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Penelitian ini akan menjawab persoalan mengenai:</p>
<ol type="1">
<li>Seberapa besar kontribusi ekspor teknologi tinggi terhadap GDP?</li>
<li>Apa saja faktor yang mempengaruhi ekspor teknologi tinggi terhadap GDP ?</li>
<li>Apa tantangan yang dihadapi dari pertumbuhan GDP dari ekspor teknologi tinggi?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan penelitian ini dirumuskan untuk memberikan manfaat bagi pemerintah dan masyarakat, dengan fokus pada pengaruh ekspor teknologi tinggi terhadap GDP di 135 Negara Tahun 2022:</p>
<p><em>1.</em> <em>Bagi Pemerintah</em></p>
<p>Memberikan rekomendasi kebijakan yang berbasis data untuk meningkatkan nilai ekpor teknologi tinggi terhadap GDP 135 negara. Mengidentifikasi strategi yang dapat digunakan pemerintah untuk mengoptimalkan pemanfaatan nilai signifikan dari ekspor teknologi tinggi, sehingga dapat mendukung pertumbuhan ekonomi yang berkelanjutan.</p>
<p><em>2.</em> <em>Bagi Masyarakat</em></p>
<p>Meningkatkan kesadaran publik mengenai peran ekspor teknologi tinggi terhadap GDBP di 135 Negara Tahun 2022. Mendorong partisipasi masyarakat dalam proses peningkatan ekspor teknologi tinggi, dengan memahami implikasi dari kebijakan tersebut terhadap kehidupan sehari-hari mereka.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p><em>1.</em> <em>Ekspor Teknologi Tinggi</em></p>
<p>Ekspor teknologi tinggi mengacu pada penjualan barang dan jasa yang menggunakan teknologi canggih dan inovatif. Menurut OECD (2021), produk teknologi tinggi mencakup sektor seperti elektronik, komunikasi, dan bioteknologi. Ekspor dalam kategori ini memiliki potensi besar untuk meningkatkan nilai tambah dan daya saing negara di pasar global.</p>
<p><em>2.</em> <em>Hubungan Antara Ekspor dan Pertumbuhan Ekonomi</em></p>
<p>Beberapa penelitian menunjukkan bahwa ekspor berkontribusi signifikan terhadap pertumbuhan ekonomi. Seperti yang dijelaskan oleh Krugman dan Obstfeld (2018), negara yang mengandalkan ekspor cenderung memiliki tingkat pertumbuhan ekonomi yang lebih tinggi karena akses mereka ke pasar global dan peningkatan permintaan untuk produk domestik.</p>
<p><em>3.</em> <em>Dampak Ekspor Teknologi Tinggi terhadap GDP</em></p>
<p>Penelitian oleh Lall (2000) menunjukkan bahwa ekspor teknologi tinggi dapat meningkatkan GDP melalui beberapa saluran, termasuk peningkatan produktivitas, penciptaan lapangan kerja, dan inovasi. Ekspor teknologi tinggi biasanya melibatkan investasi dalam penelitian dan pengembangan, yang pada gilirannya dapat meningkatkan kapasitas produksi dan daya saing.</p>
<p><em>4.</em> <em>Studi Terkait di Berbagai Negara</em></p>
<p>Penelitian oleh Lee dan Malerba (2018) mengungkapkan bahwa negara-negara dengan fokus kuat pada inovasi dan pendidikan tinggi menunjukkan hubungan positif yang signifikan antara ekspor teknologi tinggi dan GDP. Sementara itu, studi oleh Banga (2015) di negara-negara berkembang menunjukkan bahwa peningkatan ekspor teknologi tinggi dapat membantu mengurangi ketergantungan pada produk primer dan meningkatkan pertumbuhan ekonomi.</p>
<p><em>5.</em> <em>Faktor-Faktor yang Mempengaruhi Ekspor Teknologi Tinggi</em></p>
<p>Beberapa faktor berkontribusi terhadap keberhasilan ekspor teknologi tinggi, termasuk kebijakan perdagangan, kualitas infrastruktur, dan tingkat pendidikan tenaga kerja. Penelitian oleh Xu dan Wang (2020) menunjukkan bahwa investasi dalam pendidikan dan pelatihan meningkatkan kapasitas negara untuk memproduksi dan mengekspor barang-barang teknologi tinggi.</p>
<p>Studi pustaka ini menunjukkan bahwa ekspor teknologi tinggi memiliki potensi besar untuk memengaruhi GDP di berbagai negara. Meskipun banyak penelitian yang menunjukkan hubungan positif, penting untuk mempertimbangkan konteks lokal dan faktor-faktor yang dapat memengaruhi hubungan ini. Penelitian lebih lanjut diperlukan untuk menganalisis dampak spesifik dan kondisi yang mendukung pertumbuhan ekspor teknologi tinggi pada tahun 2022.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>penelitian ini menggunakan data tahun 2022, sehingga didapatkan data sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>akai <span class="ot">&lt;-</span> <span class="fu">WDI</span>(<span class="at">country =</span> <span class="st">"all"</span>, </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">indicator =</span> <span class="fu">c</span>(<span class="st">"TX.VAL.TECH.CD"</span>, <span class="st">"NY.GDP.MKTP.CD"</span>), </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">start =</span><span class="dv">2023</span>, </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">end =</span> <span class="dv">2023</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a> akai0 <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(akai)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>akai0 <span class="ot">&lt;-</span> akai0 <span class="sc">%&gt;%</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>   <span class="fu">filter</span>(TX.VAL.TECH.CD <span class="sc">!=</span> <span class="dv">0</span>, NY.GDP.MKTP.CD <span class="sc">!=</span> <span class="dv">0</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(akai0)[<span class="fu">colnames</span>(akai0) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"TX.VAL.TECH.CD"</span>, <span class="st">"NY.GDP.MKTP.CD"</span>)] <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"X"</span>, <span class="st">"Y"</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>akai0<span class="ot">&lt;-</span> akai0<span class="sc">%&gt;%</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>iso2c, <span class="sc">-</span>iso3c, <span class="sc">-</span>year)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(akai0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">country</th>
<th style="text-align: right;">X</th>
<th style="text-align: right;">Y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Andorra</td>
<td style="text-align: right;">51383658</td>
<td style="text-align: right;">3.785067e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Argentina</td>
<td style="text-align: right;">689722037</td>
<td style="text-align: right;">6.460753e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Armenia</td>
<td style="text-align: right;">822532500</td>
<td style="text-align: right;">2.408575e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aruba</td>
<td style="text-align: right;">1665839</td>
<td style="text-align: right;">3.648573e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Australia</td>
<td style="text-align: right;">7767880136</td>
<td style="text-align: right;">1.728057e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Austria</td>
<td style="text-align: right;">27308757068</td>
<td style="text-align: right;">5.116852e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Azerbaijan</td>
<td style="text-align: right;">56810637</td>
<td style="text-align: right;">7.235618e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bahamas, The</td>
<td style="text-align: right;">7099</td>
<td style="text-align: right;">1.433850e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bahrain</td>
<td style="text-align: right;">11523340</td>
<td style="text-align: right;">4.607987e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Barbados</td>
<td style="text-align: right;">16529186</td>
<td style="text-align: right;">6.720733e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Belgium</td>
<td style="text-align: right;">50647716012</td>
<td style="text-align: right;">6.447828e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Benin</td>
<td style="text-align: right;">1700350</td>
<td style="text-align: right;">1.967605e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bolivia</td>
<td style="text-align: right;">27251877</td>
<td style="text-align: right;">4.513540e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bosnia and Herzegovina</td>
<td style="text-align: right;">335043704</td>
<td style="text-align: right;">2.751478e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Botswana</td>
<td style="text-align: right;">25600565</td>
<td style="text-align: right;">1.939608e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brazil</td>
<td style="text-align: right;">8060841826</td>
<td style="text-align: right;">2.173666e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Brunei Darussalam</td>
<td style="text-align: right;">25220521</td>
<td style="text-align: right;">1.512829e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bulgaria</td>
<td style="text-align: right;">3178034114</td>
<td style="text-align: right;">1.024077e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Burkina Faso</td>
<td style="text-align: right;">8323768</td>
<td style="text-align: right;">2.032462e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cabo Verde</td>
<td style="text-align: right;">73876</td>
<td style="text-align: right;">2.533819e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Canada</td>
<td style="text-align: right;">35226982857</td>
<td style="text-align: right;">2.142471e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Central African Republic</td>
<td style="text-align: right;">221989</td>
<td style="text-align: right;">2.555492e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chile</td>
<td style="text-align: right;">1841775193</td>
<td style="text-align: right;">3.355333e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">China</td>
<td style="text-align: right;">825045389470</td>
<td style="text-align: right;">1.779478e+13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Colombia</td>
<td style="text-align: right;">873209016</td>
<td style="text-align: right;">3.634938e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Costa Rica</td>
<td style="text-align: right;">2809087758</td>
<td style="text-align: right;">8.649794e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cote d’Ivoire</td>
<td style="text-align: right;">110019023</td>
<td style="text-align: right;">7.887549e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Croatia</td>
<td style="text-align: right;">1738860511</td>
<td style="text-align: right;">8.439380e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cyprus</td>
<td style="text-align: right;">107331661</td>
<td style="text-align: right;">3.388693e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Czechia</td>
<td style="text-align: right;">46329135586</td>
<td style="text-align: right;">3.432079e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Denmark</td>
<td style="text-align: right;">16067378321</td>
<td style="text-align: right;">4.070919e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Djibouti</td>
<td style="text-align: right;">88653670</td>
<td style="text-align: right;">4.098531e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dominica</td>
<td style="text-align: right;">367176</td>
<td style="text-align: right;">6.539926e+08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dominican Republic</td>
<td style="text-align: right;">454061980</td>
<td style="text-align: right;">1.214443e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ecuador</td>
<td style="text-align: right;">106992254</td>
<td style="text-align: right;">1.188448e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Egypt, Arab Rep.</td>
<td style="text-align: right;">697613295</td>
<td style="text-align: right;">3.960025e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">El Salvador</td>
<td style="text-align: right;">296585304</td>
<td style="text-align: right;">3.401562e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Estonia</td>
<td style="text-align: right;">2085454295</td>
<td style="text-align: right;">4.129125e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Eswatini</td>
<td style="text-align: right;">3576837</td>
<td style="text-align: right;">4.442876e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ethiopia</td>
<td style="text-align: right;">9855262</td>
<td style="text-align: right;">1.636979e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">European Union</td>
<td style="text-align: right;">498151887435</td>
<td style="text-align: right;">1.859072e+13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fiji</td>
<td style="text-align: right;">1594712</td>
<td style="text-align: right;">5.442047e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Finland</td>
<td style="text-align: right;">5292503329</td>
<td style="text-align: right;">2.955323e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">France</td>
<td style="text-align: right;">115256032667</td>
<td style="text-align: right;">3.051832e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gabon</td>
<td style="text-align: right;">40040970</td>
<td style="text-align: right;">1.938840e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gambia, The</td>
<td style="text-align: right;">14930</td>
<td style="text-align: right;">2.396111e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Georgia</td>
<td style="text-align: right;">31139119</td>
<td style="text-align: right;">3.077783e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Germany</td>
<td style="text-align: right;">255687490788</td>
<td style="text-align: right;">4.525704e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ghana</td>
<td style="text-align: right;">20813123</td>
<td style="text-align: right;">7.637040e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Greece</td>
<td style="text-align: right;">3023255566</td>
<td style="text-align: right;">2.434983e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Grenada</td>
<td style="text-align: right;">420417</td>
<td style="text-align: right;">1.316733e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guatemala</td>
<td style="text-align: right;">376979755</td>
<td style="text-align: right;">1.044502e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guyana</td>
<td style="text-align: right;">9073399</td>
<td style="text-align: right;">1.715951e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hong Kong SAR, China</td>
<td style="text-align: right;">369163546379</td>
<td style="text-align: right;">3.808122e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hungary</td>
<td style="text-align: right;">24367700793</td>
<td style="text-align: right;">2.123889e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Iceland</td>
<td style="text-align: right;">453683000</td>
<td style="text-align: right;">3.132512e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">India</td>
<td style="text-align: right;">40942449667</td>
<td style="text-align: right;">3.567552e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Indonesia</td>
<td style="text-align: right;">10509333468</td>
<td style="text-align: right;">1.371171e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ireland</td>
<td style="text-align: right;">91363721988</td>
<td style="text-align: right;">5.513949e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Israel</td>
<td style="text-align: right;">18160193649</td>
<td style="text-align: right;">5.136111e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Italy</td>
<td style="text-align: right;">52167641514</td>
<td style="text-align: right;">2.300941e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jamaica</td>
<td style="text-align: right;">1222621</td>
<td style="text-align: right;">1.942336e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Japan</td>
<td style="text-align: right;">102601446852</td>
<td style="text-align: right;">4.204495e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jordan</td>
<td style="text-align: right;">177694397</td>
<td style="text-align: right;">5.096748e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kazakhstan</td>
<td style="text-align: right;">5145671171</td>
<td style="text-align: right;">2.626419e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kenya</td>
<td style="text-align: right;">60148845</td>
<td style="text-align: right;">1.080386e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kuwait</td>
<td style="text-align: right;">54309594</td>
<td style="text-align: right;">1.637049e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kyrgyz Republic</td>
<td style="text-align: right;">195275130</td>
<td style="text-align: right;">1.398763e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Latvia</td>
<td style="text-align: right;">2076324272</td>
<td style="text-align: right;">4.224785e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Liberia</td>
<td style="text-align: right;">97955</td>
<td style="text-align: right;">4.240000e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lithuania</td>
<td style="text-align: right;">3740035230</td>
<td style="text-align: right;">7.978988e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Luxembourg</td>
<td style="text-align: right;">801169826</td>
<td style="text-align: right;">8.575501e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Madagascar</td>
<td style="text-align: right;">3982231</td>
<td style="text-align: right;">1.579011e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Malawi</td>
<td style="text-align: right;">4133308</td>
<td style="text-align: right;">1.271215e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Malaysia</td>
<td style="text-align: right;">127032168259</td>
<td style="text-align: right;">3.997052e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Maldives</td>
<td style="text-align: right;">646</td>
<td style="text-align: right;">6.590894e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Malta</td>
<td style="text-align: right;">1234225995</td>
<td style="text-align: right;">2.232864e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mauritania</td>
<td style="text-align: right;">3637891</td>
<td style="text-align: right;">1.065171e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mauritius</td>
<td style="text-align: right;">6408555</td>
<td style="text-align: right;">1.464452e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mexico</td>
<td style="text-align: right;">81456744669</td>
<td style="text-align: right;">1.789114e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Moldova</td>
<td style="text-align: right;">28885013</td>
<td style="text-align: right;">1.653944e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Montenegro</td>
<td style="text-align: right;">15199424</td>
<td style="text-align: right;">7.530593e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Morocco</td>
<td style="text-align: right;">1723700823</td>
<td style="text-align: right;">1.444171e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mozambique</td>
<td style="text-align: right;">16632000</td>
<td style="text-align: right;">2.095422e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Myanmar</td>
<td style="text-align: right;">190414450</td>
<td style="text-align: right;">6.675762e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Namibia</td>
<td style="text-align: right;">845964</td>
<td style="text-align: right;">1.235103e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Netherlands</td>
<td style="text-align: right;">110952318467</td>
<td style="text-align: right;">1.154361e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">New Zealand</td>
<td style="text-align: right;">823527942</td>
<td style="text-align: right;">2.521755e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nicaragua</td>
<td style="text-align: right;">22949838</td>
<td style="text-align: right;">1.782922e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Niger</td>
<td style="text-align: right;">2603432</td>
<td style="text-align: right;">1.681917e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nigeria</td>
<td style="text-align: right;">65160240</td>
<td style="text-align: right;">3.638463e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">North Macedonia</td>
<td style="text-align: right;">387658985</td>
<td style="text-align: right;">1.576362e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Norway</td>
<td style="text-align: right;">5957981536</td>
<td style="text-align: right;">4.853108e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oman</td>
<td style="text-align: right;">441801906</td>
<td style="text-align: right;">1.088109e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pakistan</td>
<td style="text-align: right;">384348995</td>
<td style="text-align: right;">3.379123e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Panama</td>
<td style="text-align: right;">1339544</td>
<td style="text-align: right;">8.331818e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Paraguay</td>
<td style="text-align: right;">162697885</td>
<td style="text-align: right;">4.295626e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Peru</td>
<td style="text-align: right;">264161339</td>
<td style="text-align: right;">2.676032e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Philippines</td>
<td style="text-align: right;">37090950135</td>
<td style="text-align: right;">4.371464e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Poland</td>
<td style="text-align: right;">29592130553</td>
<td style="text-align: right;">8.092007e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Portugal</td>
<td style="text-align: right;">4196056729</td>
<td style="text-align: right;">2.891143e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Qatar</td>
<td style="text-align: right;">245655998</td>
<td style="text-align: right;">2.130028e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Romania</td>
<td style="text-align: right;">9724366747</td>
<td style="text-align: right;">3.507759e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Samoa</td>
<td style="text-align: right;">396638</td>
<td style="text-align: right;">9.381894e+08</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sao Tome and Principe</td>
<td style="text-align: right;">70979</td>
<td style="text-align: right;">6.789763e+08</td>
</tr>
<tr class="even">
<td style="text-align: left;">Saudi Arabia</td>
<td style="text-align: right;">3641055220</td>
<td style="text-align: right;">1.067583e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Senegal</td>
<td style="text-align: right;">22544982</td>
<td style="text-align: right;">3.084833e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Serbia</td>
<td style="text-align: right;">1358732901</td>
<td style="text-align: right;">8.134266e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Seychelles</td>
<td style="text-align: right;">711</td>
<td style="text-align: right;">2.141450e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Singapore</td>
<td style="text-align: right;">197387649519</td>
<td style="text-align: right;">5.014275e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Slovak Republic</td>
<td style="text-align: right;">10122798808</td>
<td style="text-align: right;">1.329083e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Slovenia</td>
<td style="text-align: right;">4206749873</td>
<td style="text-align: right;">6.914847e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">South Africa</td>
<td style="text-align: right;">2215402355</td>
<td style="text-align: right;">3.806993e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Spain</td>
<td style="text-align: right;">25806027599</td>
<td style="text-align: right;">1.620091e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sri Lanka</td>
<td style="text-align: right;">112381343</td>
<td style="text-align: right;">8.435686e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">St.&nbsp;Vincent and the Grenadines</td>
<td style="text-align: right;">535939</td>
<td style="text-align: right;">1.065963e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Suriname</td>
<td style="text-align: right;">5300351</td>
<td style="text-align: right;">3.455146e+09</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sweden</td>
<td style="text-align: right;">25152736881</td>
<td style="text-align: right;">5.849605e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Switzerland</td>
<td style="text-align: right;">84443768583</td>
<td style="text-align: right;">8.849404e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tanzania</td>
<td style="text-align: right;">43110701</td>
<td style="text-align: right;">7.906240e+10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Thailand</td>
<td style="text-align: right;">54112421409</td>
<td style="text-align: right;">5.149687e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Togo</td>
<td style="text-align: right;">2229077</td>
<td style="text-align: right;">9.171262e+09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tunisia</td>
<td style="text-align: right;">1198528314</td>
<td style="text-align: right;">4.852960e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Turkiye</td>
<td style="text-align: right;">8461609431</td>
<td style="text-align: right;">1.118253e+12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ukraine</td>
<td style="text-align: right;">728946823</td>
<td style="text-align: right;">1.787570e+11</td>
</tr>
<tr class="even">
<td style="text-align: left;">United Arab Emirates</td>
<td style="text-align: right;">3183641981</td>
<td style="text-align: right;">5.141304e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">United Kingdom</td>
<td style="text-align: right;">82372118999</td>
<td style="text-align: right;">3.380855e+12</td>
</tr>
<tr class="even">
<td style="text-align: left;">United States</td>
<td style="text-align: right;">208514376770</td>
<td style="text-align: right;">2.772071e+13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Uruguay</td>
<td style="text-align: right;">188475643</td>
<td style="text-align: right;">7.724083e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Uzbekistan</td>
<td style="text-align: right;">200637379</td>
<td style="text-align: right;">1.015918e+11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zambia</td>
<td style="text-align: right;">14668136</td>
<td style="text-align: right;">2.757796e+10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zimbabwe</td>
<td style="text-align: right;">10554661</td>
<td style="text-align: right;">3.523137e+10</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_xlsx</span>(akai0,<span class="st">"akai0.xlsx"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(akai0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>akai0<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"akai0.xlsx"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>akai0)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = akai0)

Residuals:
       Min         1Q     Median         3Q        Max 
-8.956e+12 -1.742e+11 -1.570e+11 -5.640e+10  2.237e+13 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 1.773e+11  2.096e+11   0.846    0.399    
X           2.481e+01  2.101e+00  11.809   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.308e+12 on 130 degrees of freedom
Multiple R-squared:  0.5175,    Adjusted R-squared:  0.5138 
F-statistic: 139.4 on 1 and 130 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>akai0<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(akai0<span class="sc">$</span>Y,akai0<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"GDP"</span>,<span class="at">ylab=</span><span class="st">"error"</span>,<span class="at">col=</span><span class="st">'BLUE'</span>,<span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>akai0<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(akai0<span class="sc">$</span>X,akai0<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"Ekspor Teknologi Tinggi"</span>,<span class="at">ylab=</span><span class="st">"error"</span>,<span class="at">col=</span><span class="st">'red'</span>,<span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Pada plot residual, saya melihat bahwa data tidak tersebar merata di sekitar garis nol, dengan beberapa titik yang jauh dari garis, terutama di sisi kanan plot. Ini menunjukkan adanya data dengan pengaruh besar atau prediksi yang kurang akurat. Sebagian besar residual memiliki nilai kecil, tapi ada juga yang sangat besar, yang mengarah pada kemungkinan adanya heteroskedastisitas, di mana variasi residual meningkat seiring dengan naiknya GDP. Tampaknya ada pola di mana residual lebih besar pada GDP yang tinggi, yang bisa melanggar asumsi regresi OLS, yang mengharuskan varians residual tetap konstan. Untuk memastikan ini, saya perlu melakukan uji formal seperti Breusch-Pagan Test untuk mengonfirmasi apakah heteroskedastisitas memang ada.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  reg
BP = 9.2848, df = 1, p-value = 0.002311</code></pre>
</div>
</div>
<p>Hasil uji Breusch-Pagan yang saya lakukan menunjukkan adanya heteroskedastisitas dalam model regresi saya. Nilai BP (Breusch-Pagan Test Statistic) yang saya peroleh adalah 9.5309, yang menunjukkan adanya bukti kuat untuk heteroskedastisitas. Semakin besar nilai ini, semakin jelas bahwa masalah tersebut ada. Derajat kebebasan (df) adalah 1, sesuai dengan jumlah variabel independen dalam model saya. Sementara itu, p-value yang didapatkan adalah 0.00202, yang lebih kecil dari 0.05. Ini berarti heteroskedastisitas terjadi secara signifikan, yang mengindikasikan bahwa varians residual tidak konstan, dan ini melanggar asumsi regresi OLS. Untuk mengatasi masalah ini, saya bisa menggunakan Weighted Least Squares (WLS), metode yang sering digunakan untuk menangani heteroskedastisitas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>weights <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> <span class="fu">fitted</span>(reg)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>wls_akai0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X, <span class="at">data =</span> akai0, <span class="at">weights =</span> weights)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wls_akai0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = akai0, weights = weights)

Weighted Residuals:
    Min      1Q  Median      3Q     Max 
-1.4027 -0.4222 -0.3314  0.0865  4.7806 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 7.739e+10  1.863e+10   4.155 5.86e-05 ***
X           3.630e+01  4.806e+00   7.553 6.66e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.962 on 130 degrees of freedom
Multiple R-squared:  0.305, Adjusted R-squared:  0.2997 
F-statistic: 57.05 on 1 and 130 DF,  p-value: 6.662e-12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(wls_akai0), <span class="fu">resid</span>(wls_akai0), <span class="at">main =</span> <span class="st">"Residuals vs Fitted"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Grafik Residuals vs Fitted menunjukkan bahwa sebagian besar residual tersebar di sekitar nol pada nilai fitted rendah, namun ada beberapa residual besar pada nilai fitted tinggi, yang mengindikasikan kemungkinan adanya heteroskedastisitas. Selain itu, beberapa titik jauh dari kumpulan data utama, terutama pada GDP yang sangat tinggi, kemungkinan merupakan outlier atau leverage points, seperti negara-negara dengan GDP besar. Untuk mengatasi masalah ini, saya dapat menggunakan Cook’s Distance untuk mengidentifikasi outlier dan mencoba transformasi logaritmik pada data untuk mengurangi skala variabel besar dan memperbaiki distribusi residual.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>akai0<span class="sc">$</span>log_Y <span class="ot">&lt;-</span> <span class="fu">log</span>(akai0<span class="sc">$</span>Y)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>akai0<span class="sc">$</span>log_X <span class="ot">&lt;-</span> <span class="fu">log</span>(akai0<span class="sc">$</span>X)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>log_akai0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(log_Y <span class="sc">~</span> log_X, <span class="at">data =</span> akai0)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(log_akai0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_Y ~ log_X, data = akai0)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.5777 -0.7914 -0.0435  0.7127  3.0292 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 16.77253    0.44801   37.44   &lt;2e-16 ***
log_X        0.43383    0.02252   19.27   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.132 on 130 degrees of freedom
Multiple R-squared:  0.7406,    Adjusted R-squared:  0.7386 
F-statistic: 371.2 on 1 and 130 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(log_akai0), <span class="fu">resid</span>(log_akai0), <span class="at">main =</span> <span class="st">"Residuals vs Fitted"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>akai0<span class="ot">&lt;-</span> akai0<span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>X, <span class="sc">-</span>Y)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(akai0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">country</th>
<th style="text-align: right;">m</th>
<th style="text-align: right;">log_Y</th>
<th style="text-align: right;">log_X</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Andorra</td>
<td style="text-align: right;">-1.747769e+11</td>
<td style="text-align: right;">22.05433</td>
<td style="text-align: right;">17.754831</td>
</tr>
<tr class="even">
<td style="text-align: left;">Argentina</td>
<td style="text-align: right;">4.516751e+11</td>
<td style="text-align: right;">27.19418</td>
<td style="text-align: right;">20.351799</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Armenia</td>
<td style="text-align: right;">-1.736097e+11</td>
<td style="text-align: right;">23.90489</td>
<td style="text-align: right;">20.527899</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aruba</td>
<td style="text-align: right;">-1.736798e+11</td>
<td style="text-align: right;">22.01760</td>
<td style="text-align: right;">14.325840</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Australia</td>
<td style="text-align: right;">1.358037e+12</td>
<td style="text-align: right;">28.17802</td>
<td style="text-align: right;">22.773263</td>
</tr>
<tr class="even">
<td style="text-align: left;">Austria</td>
<td style="text-align: right;">-3.431764e+11</td>
<td style="text-align: right;">26.96098</td>
<td style="text-align: right;">24.030473</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Azerbaijan</td>
<td style="text-align: right;">-1.063405e+11</td>
<td style="text-align: right;">25.00487</td>
<td style="text-align: right;">17.855234</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bahamas, The</td>
<td style="text-align: right;">-1.629488e+11</td>
<td style="text-align: right;">23.38621</td>
<td style="text-align: right;">8.867709</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bahrain</td>
<td style="text-align: right;">-1.314931e+11</td>
<td style="text-align: right;">24.55364</td>
<td style="text-align: right;">16.259885</td>
</tr>
<tr class="even">
<td style="text-align: left;">Barbados</td>
<td style="text-align: right;">-1.709765e+11</td>
<td style="text-align: right;">22.62846</td>
<td style="text-align: right;">16.620638</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Belgium</td>
<td style="text-align: right;">-7.891562e+11</td>
<td style="text-align: right;">27.19218</td>
<td style="text-align: right;">24.648160</td>
</tr>
<tr class="even">
<td style="text-align: left;">Benin</td>
<td style="text-align: right;">-1.576532e+11</td>
<td style="text-align: right;">23.70267</td>
<td style="text-align: right;">14.346345</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bolivia</td>
<td style="text-align: right;">-1.328278e+11</td>
<td style="text-align: right;">24.53293</td>
<td style="text-align: right;">17.120633</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bosnia and Herzegovina</td>
<td style="text-align: right;">-1.580853e+11</td>
<td style="text-align: right;">24.03799</td>
<td style="text-align: right;">19.629772</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Botswana</td>
<td style="text-align: right;">-1.585262e+11</td>
<td style="text-align: right;">23.68834</td>
<td style="text-align: right;">17.058125</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brazil</td>
<td style="text-align: right;">1.796376e+12</td>
<td style="text-align: right;">28.40744</td>
<td style="text-align: right;">22.810284</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Brunei Darussalam</td>
<td style="text-align: right;">-1.627845e+11</td>
<td style="text-align: right;">23.43983</td>
<td style="text-align: right;">17.043169</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bulgaria</td>
<td style="text-align: right;">-1.537316e+11</td>
<td style="text-align: right;">25.35223</td>
<td style="text-align: right;">21.879529</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Burkina Faso</td>
<td style="text-align: right;">-1.571690e+11</td>
<td style="text-align: right;">23.73510</td>
<td style="text-align: right;">15.934626</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cabo Verde</td>
<td style="text-align: right;">-1.747551e+11</td>
<td style="text-align: right;">21.65299</td>
<td style="text-align: right;">11.210143</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Canada</td>
<td style="text-align: right;">1.091145e+12</td>
<td style="text-align: right;">28.39298</td>
<td style="text-align: right;">24.285078</td>
</tr>
<tr class="even">
<td style="text-align: left;">Central African Republic</td>
<td style="text-align: right;">-1.747371e+11</td>
<td style="text-align: right;">21.66151</td>
<td style="text-align: right;">12.310383</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chile</td>
<td style="text-align: right;">1.125488e+11</td>
<td style="text-align: right;">26.53899</td>
<td style="text-align: right;">21.333996</td>
</tr>
<tr class="even">
<td style="text-align: left;">China</td>
<td style="text-align: right;">-2.853217e+12</td>
<td style="text-align: right;">30.50993</td>
<td style="text-align: right;">27.438704</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Colombia</td>
<td style="text-align: right;">1.645410e+11</td>
<td style="text-align: right;">26.61903</td>
<td style="text-align: right;">20.587685</td>
</tr>
<tr class="even">
<td style="text-align: left;">Costa Rica</td>
<td style="text-align: right;">-1.604872e+11</td>
<td style="text-align: right;">25.18339</td>
<td style="text-align: right;">21.756126</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cote d’Ivoire</td>
<td style="text-align: right;">-1.011413e+11</td>
<td style="text-align: right;">25.09114</td>
<td style="text-align: right;">18.516164</td>
</tr>
<tr class="even">
<td style="text-align: left;">Croatia</td>
<td style="text-align: right;">-1.360372e+11</td>
<td style="text-align: right;">25.15876</td>
<td style="text-align: right;">21.276496</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cyprus</td>
<td style="text-align: right;">-1.460632e+11</td>
<td style="text-align: right;">24.24630</td>
<td style="text-align: right;">18.491434</td>
</tr>
<tr class="even">
<td style="text-align: left;">Czechia</td>
<td style="text-align: right;">-9.835801e+11</td>
<td style="text-align: right;">26.56160</td>
<td style="text-align: right;">24.559037</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Denmark</td>
<td style="text-align: right;">-1.688528e+11</td>
<td style="text-align: right;">26.73230</td>
<td style="text-align: right;">23.500057</td>
</tr>
<tr class="even">
<td style="text-align: left;">Djibouti</td>
<td style="text-align: right;">-1.753882e+11</td>
<td style="text-align: right;">22.13389</td>
<td style="text-align: right;">18.300248</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dominica</td>
<td style="text-align: right;">-1.766422e+11</td>
<td style="text-align: right;">20.29861</td>
<td style="text-align: right;">12.813597</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dominican Republic</td>
<td style="text-align: right;">-6.710881e+10</td>
<td style="text-align: right;">25.52272</td>
<td style="text-align: right;">19.933744</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ecuador</td>
<td style="text-align: right;">-6.109690e+10</td>
<td style="text-align: right;">25.50108</td>
<td style="text-align: right;">18.488267</td>
</tr>
<tr class="even">
<td style="text-align: left;">Egypt, Arab Rep.</td>
<td style="text-align: right;">2.014065e+11</td>
<td style="text-align: right;">26.70469</td>
<td style="text-align: right;">20.363176</td>
</tr>
<tr class="odd">
<td style="text-align: left;">El Salvador</td>
<td style="text-align: right;">-1.506302e+11</td>
<td style="text-align: right;">24.25009</td>
<td style="text-align: right;">19.507845</td>
</tr>
<tr class="even">
<td style="text-align: left;">Estonia</td>
<td style="text-align: right;">-1.877393e+11</td>
<td style="text-align: right;">24.44392</td>
<td style="text-align: right;">21.458253</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Eswatini</td>
<td style="text-align: right;">-1.729329e+11</td>
<td style="text-align: right;">22.21457</td>
<td style="text-align: right;">15.089989</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ethiopia</td>
<td style="text-align: right;">-1.383367e+10</td>
<td style="text-align: right;">25.82129</td>
<td style="text-align: right;">16.103516</td>
</tr>
<tr class="odd">
<td style="text-align: left;">European Union</td>
<td style="text-align: right;">6.053478e+12</td>
<td style="text-align: right;">30.55368</td>
<td style="text-align: right;">26.934171</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fiji</td>
<td style="text-align: right;">-1.718846e+11</td>
<td style="text-align: right;">22.41742</td>
<td style="text-align: right;">14.282204</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Finland</td>
<td style="text-align: right;">-1.307032e+10</td>
<td style="text-align: right;">26.41204</td>
<td style="text-align: right;">22.389557</td>
</tr>
<tr class="even">
<td style="text-align: left;">France</td>
<td style="text-align: right;">1.485566e+10</td>
<td style="text-align: right;">28.74676</td>
<td style="text-align: right;">25.470422</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gabon</td>
<td style="text-align: right;">-1.588922e+11</td>
<td style="text-align: right;">23.68794</td>
<td style="text-align: right;">17.505414</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gambia, The</td>
<td style="text-align: right;">-1.748913e+11</td>
<td style="text-align: right;">21.59711</td>
<td style="text-align: right;">9.611128</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Georgia</td>
<td style="text-align: right;">-1.472819e+11</td>
<td style="text-align: right;">24.15006</td>
<td style="text-align: right;">17.253975</td>
</tr>
<tr class="even">
<td style="text-align: left;">Germany</td>
<td style="text-align: right;">-1.995604e+12</td>
<td style="text-align: right;">29.14079</td>
<td style="text-align: right;">26.267222</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ghana</td>
<td style="text-align: right;">-1.014331e+11</td>
<td style="text-align: right;">25.05886</td>
<td style="text-align: right;">16.851094</td>
</tr>
<tr class="even">
<td style="text-align: left;">Greece</td>
<td style="text-align: right;">-8.800610e+09</td>
<td style="text-align: right;">26.21838</td>
<td style="text-align: right;">21.829600</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Grenada</td>
<td style="text-align: right;">-1.759808e+11</td>
<td style="text-align: right;">20.99842</td>
<td style="text-align: right;">12.949002</td>
</tr>
<tr class="even">
<td style="text-align: left;">Guatemala</td>
<td style="text-align: right;">-8.219034e+10</td>
<td style="text-align: right;">25.37198</td>
<td style="text-align: right;">19.747702</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Guyana</td>
<td style="text-align: right;">-1.603527e+11</td>
<td style="text-align: right;">23.56582</td>
<td style="text-align: right;">16.020858</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hong Kong SAR, China</td>
<td style="text-align: right;">-8.956020e+12</td>
<td style="text-align: right;">26.66557</td>
<td style="text-align: right;">26.634506</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hungary</td>
<td style="text-align: right;">-5.695003e+11</td>
<td style="text-align: right;">26.08168</td>
<td style="text-align: right;">23.916524</td>
</tr>
<tr class="even">
<td style="text-align: left;">Iceland</td>
<td style="text-align: right;">-1.572186e+11</td>
<td style="text-align: right;">24.16769</td>
<td style="text-align: right;">19.932909</td>
</tr>
<tr class="odd">
<td style="text-align: left;">India</td>
<td style="text-align: right;">2.374416e+12</td>
<td style="text-align: right;">28.90290</td>
<td style="text-align: right;">24.435433</td>
</tr>
<tr class="even">
<td style="text-align: left;">Indonesia</td>
<td style="text-align: right;">9.331305e+11</td>
<td style="text-align: right;">27.94669</td>
<td style="text-align: right;">23.075530</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ireland</td>
<td style="text-align: right;">-1.892774e+12</td>
<td style="text-align: right;">27.03572</td>
<td style="text-align: right;">25.238114</td>
</tr>
<tr class="even">
<td style="text-align: left;">Israel</td>
<td style="text-align: right;">-1.142598e+11</td>
<td style="text-align: right;">26.96473</td>
<td style="text-align: right;">23.622498</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Italy</td>
<td style="text-align: right;">8.292904e+11</td>
<td style="text-align: right;">28.46434</td>
<td style="text-align: right;">24.677728</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jamaica</td>
<td style="text-align: right;">-1.578941e+11</td>
<td style="text-align: right;">23.68974</td>
<td style="text-align: right;">14.016507</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Japan</td>
<td style="text-align: right;">1.481500e+12</td>
<td style="text-align: right;">29.06718</td>
<td style="text-align: right;">25.354118</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jordan</td>
<td style="text-align: right;">-1.307285e+11</td>
<td style="text-align: right;">24.65445</td>
<td style="text-align: right;">18.995576</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kazakhstan</td>
<td style="text-align: right;">-4.231762e+10</td>
<td style="text-align: right;">26.29406</td>
<td style="text-align: right;">22.361422</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kenya</td>
<td style="text-align: right;">-7.074088e+10</td>
<td style="text-align: right;">25.40575</td>
<td style="text-align: right;">17.912333</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kuwait</td>
<td style="text-align: right;">-1.492971e+10</td>
<td style="text-align: right;">25.82133</td>
<td style="text-align: right;">17.810212</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kyrgyz Republic</td>
<td style="text-align: right;">-1.681445e+11</td>
<td style="text-align: right;">23.36144</td>
<td style="text-align: right;">19.089920</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Latvia</td>
<td style="text-align: right;">-1.865562e+11</td>
<td style="text-align: right;">24.46682</td>
<td style="text-align: right;">21.453865</td>
</tr>
<tr class="even">
<td style="text-align: left;">Liberia</td>
<td style="text-align: right;">-1.730495e+11</td>
<td style="text-align: right;">22.16783</td>
<td style="text-align: right;">11.492263</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lithuania</td>
<td style="text-align: right;">-1.902935e+11</td>
<td style="text-align: right;">25.10266</td>
<td style="text-align: right;">22.042361</td>
</tr>
<tr class="even">
<td style="text-align: left;">Luxembourg</td>
<td style="text-align: right;">-1.114104e+11</td>
<td style="text-align: right;">25.17476</td>
<td style="text-align: right;">20.501583</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Madagascar</td>
<td style="text-align: right;">-1.615958e+11</td>
<td style="text-align: right;">23.48265</td>
<td style="text-align: right;">15.197353</td>
</tr>
<tr class="even">
<td style="text-align: left;">Malawi</td>
<td style="text-align: right;">-1.646775e+11</td>
<td style="text-align: right;">23.26582</td>
<td style="text-align: right;">15.234589</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Malaysia</td>
<td style="text-align: right;">-2.929456e+12</td>
<td style="text-align: right;">26.71399</td>
<td style="text-align: right;">25.567706</td>
</tr>
<tr class="even">
<td style="text-align: left;">Maldives</td>
<td style="text-align: right;">-1.706962e+11</td>
<td style="text-align: right;">22.60895</td>
<td style="text-align: right;">6.470800</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Malta</td>
<td style="text-align: right;">-1.855816e+11</td>
<td style="text-align: right;">23.82914</td>
<td style="text-align: right;">20.933710</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mauritania</td>
<td style="text-align: right;">-1.667256e+11</td>
<td style="text-align: right;">23.08899</td>
<td style="text-align: right;">15.106915</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mauritius</td>
<td style="text-align: right;">-1.628016e+11</td>
<td style="text-align: right;">23.40733</td>
<td style="text-align: right;">15.673144</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mexico</td>
<td style="text-align: right;">-4.092464e+11</td>
<td style="text-align: right;">28.21274</td>
<td style="text-align: right;">25.123338</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Moldova</td>
<td style="text-align: right;">-1.614643e+11</td>
<td style="text-align: right;">23.52901</td>
<td style="text-align: right;">17.178833</td>
</tr>
<tr class="even">
<td style="text-align: left;">Montenegro</td>
<td style="text-align: right;">-1.701336e+11</td>
<td style="text-align: right;">22.74224</td>
<td style="text-align: right;">16.536768</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Morocco</td>
<td style="text-align: right;">-7.563778e+10</td>
<td style="text-align: right;">25.69597</td>
<td style="text-align: right;">21.267740</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mozambique</td>
<td style="text-align: right;">-1.567455e+11</td>
<td style="text-align: right;">23.76561</td>
<td style="text-align: right;">16.626839</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Myanmar</td>
<td style="text-align: right;">-1.152539e+11</td>
<td style="text-align: right;">24.92433</td>
<td style="text-align: right;">19.064714</td>
</tr>
<tr class="even">
<td style="text-align: left;">Namibia</td>
<td style="text-align: right;">-1.649570e+11</td>
<td style="text-align: right;">23.23700</td>
<td style="text-align: right;">13.648232</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Netherlands</td>
<td style="text-align: right;">-1.775833e+12</td>
<td style="text-align: right;">27.77457</td>
<td style="text-align: right;">25.432366</td>
</tr>
<tr class="even">
<td style="text-align: left;">New Zealand</td>
<td style="text-align: right;">5.445537e+10</td>
<td style="text-align: right;">26.25339</td>
<td style="text-align: right;">20.529108</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nicaragua</td>
<td style="text-align: right;">-1.600273e+11</td>
<td style="text-align: right;">23.60410</td>
<td style="text-align: right;">16.948821</td>
</tr>
<tr class="even">
<td style="text-align: left;">Niger</td>
<td style="text-align: right;">-1.605325e+11</td>
<td style="text-align: right;">23.54579</td>
<td style="text-align: right;">14.772341</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nigeria</td>
<td style="text-align: right;">1.849425e+11</td>
<td style="text-align: right;">26.62000</td>
<td style="text-align: right;">17.992360</td>
</tr>
<tr class="even">
<td style="text-align: left;">North Macedonia</td>
<td style="text-align: right;">-1.711419e+11</td>
<td style="text-align: right;">23.48097</td>
<td style="text-align: right;">19.775637</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Norway</td>
<td style="text-align: right;">1.601966e+11</td>
<td style="text-align: right;">26.90806</td>
<td style="text-align: right;">22.507998</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oman</td>
<td style="text-align: right;">-7.943797e+10</td>
<td style="text-align: right;">25.41288</td>
<td style="text-align: right;">19.906372</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pakistan</td>
<td style="text-align: right;">1.510889e+11</td>
<td style="text-align: right;">26.54605</td>
<td style="text-align: right;">19.767062</td>
</tr>
<tr class="even">
<td style="text-align: left;">Panama</td>
<td style="text-align: right;">-9.400214e+10</td>
<td style="text-align: right;">25.14593</td>
<td style="text-align: right;">14.107840</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Paraguay</td>
<td style="text-align: right;">-1.383676e+11</td>
<td style="text-align: right;">24.48345</td>
<td style="text-align: right;">18.907406</td>
</tr>
<tr class="even">
<td style="text-align: left;">Peru</td>
<td style="text-align: right;">8.376190e+10</td>
<td style="text-align: right;">26.31277</td>
<td style="text-align: right;">19.392071</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Philippines</td>
<td style="text-align: right;">-6.604273e+11</td>
<td style="text-align: right;">26.80353</td>
<td style="text-align: right;">24.336639</td>
</tr>
<tr class="even">
<td style="text-align: left;">Poland</td>
<td style="text-align: right;">-1.023151e+11</td>
<td style="text-align: right;">27.41931</td>
<td style="text-align: right;">24.110774</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Portugal</td>
<td style="text-align: right;">7.716249e+09</td>
<td style="text-align: right;">26.39009</td>
<td style="text-align: right;">22.157411</td>
</tr>
<tr class="even">
<td style="text-align: left;">Qatar</td>
<td style="text-align: right;">2.962061e+10</td>
<td style="text-align: right;">26.08457</td>
<td style="text-align: right;">19.319443</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Romania</td>
<td style="text-align: right;">-6.778851e+10</td>
<td style="text-align: right;">26.58341</td>
<td style="text-align: right;">22.997901</td>
</tr>
<tr class="even">
<td style="text-align: left;">Samoa</td>
<td style="text-align: right;">-1.763587e+11</td>
<td style="text-align: right;">20.65946</td>
<td style="text-align: right;">12.890779</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sao Tome and Principe</td>
<td style="text-align: right;">-1.766099e+11</td>
<td style="text-align: right;">20.33610</td>
<td style="text-align: right;">11.170139</td>
</tr>
<tr class="even">
<td style="text-align: left;">Saudi Arabia</td>
<td style="text-align: right;">7.999554e+11</td>
<td style="text-align: right;">27.69642</td>
<td style="text-align: right;">22.015539</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Senegal</td>
<td style="text-align: right;">-1.469981e+11</td>
<td style="text-align: right;">24.15235</td>
<td style="text-align: right;">16.931023</td>
</tr>
<tr class="even">
<td style="text-align: left;">Serbia</td>
<td style="text-align: right;">-1.296568e+11</td>
<td style="text-align: right;">25.12194</td>
<td style="text-align: right;">21.029818</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Seychelles</td>
<td style="text-align: right;">-1.751456e+11</td>
<td style="text-align: right;">21.48475</td>
<td style="text-align: right;">6.566672</td>
</tr>
<tr class="even">
<td style="text-align: left;">Singapore</td>
<td style="text-align: right;">-4.573367e+12</td>
<td style="text-align: right;">26.94072</td>
<td style="text-align: right;">26.008435</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Slovak Republic</td>
<td style="text-align: right;">-2.955418e+11</td>
<td style="text-align: right;">25.61293</td>
<td style="text-align: right;">23.038056</td>
</tr>
<tr class="even">
<td style="text-align: left;">Slovenia</td>
<td style="text-align: right;">-2.125149e+11</td>
<td style="text-align: right;">24.95952</td>
<td style="text-align: right;">22.159956</td>
</tr>
<tr class="odd">
<td style="text-align: left;">South Africa</td>
<td style="text-align: right;">1.484445e+11</td>
<td style="text-align: right;">26.66528</td>
<td style="text-align: right;">21.518700</td>
</tr>
<tr class="even">
<td style="text-align: left;">Spain</td>
<td style="text-align: right;">8.025143e+11</td>
<td style="text-align: right;">28.11350</td>
<td style="text-align: right;">23.973874</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sri Lanka</td>
<td style="text-align: right;">-9.571858e+10</td>
<td style="text-align: right;">25.15832</td>
<td style="text-align: right;">18.537409</td>
</tr>
<tr class="even">
<td style="text-align: left;">St.&nbsp;Vincent and the Grenadines</td>
<td style="text-align: right;">-1.762344e+11</td>
<td style="text-align: right;">20.78714</td>
<td style="text-align: right;">13.191776</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Suriname</td>
<td style="text-align: right;">-1.739634e+11</td>
<td style="text-align: right;">21.96313</td>
<td style="text-align: right;">15.483284</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sweden</td>
<td style="text-align: right;">-2.164067e+11</td>
<td style="text-align: right;">27.09481</td>
<td style="text-align: right;">23.948232</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Switzerland</td>
<td style="text-align: right;">-1.387533e+12</td>
<td style="text-align: right;">27.50879</td>
<td style="text-align: right;">25.159352</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tanzania</td>
<td style="text-align: right;">-9.929432e+10</td>
<td style="text-align: right;">25.09350</td>
<td style="text-align: right;">17.579282</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Thailand</td>
<td style="text-align: right;">-1.004935e+12</td>
<td style="text-align: right;">26.96737</td>
<td style="text-align: right;">24.714330</td>
</tr>
<tr class="even">
<td style="text-align: left;">Togo</td>
<td style="text-align: right;">-1.681711e+11</td>
<td style="text-align: right;">22.93934</td>
<td style="text-align: right;">14.617098</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tunisia</td>
<td style="text-align: right;">-1.584949e+11</td>
<td style="text-align: right;">24.60544</td>
<td style="text-align: right;">20.904360</td>
</tr>
<tr class="even">
<td style="text-align: left;">Turkiye</td>
<td style="text-align: right;">7.310197e+11</td>
<td style="text-align: right;">27.74279</td>
<td style="text-align: right;">22.858805</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ukraine</td>
<td style="text-align: right;">-1.661641e+10</td>
<td style="text-align: right;">25.90929</td>
<td style="text-align: right;">20.407111</td>
</tr>
<tr class="even">
<td style="text-align: left;">United Arab Emirates</td>
<td style="text-align: right;">2.578520e+11</td>
<td style="text-align: right;">26.96574</td>
<td style="text-align: right;">21.881292</td>
</tr>
<tr class="odd">
<td style="text-align: left;">United Kingdom</td>
<td style="text-align: right;">1.159782e+12</td>
<td style="text-align: right;">28.84915</td>
<td style="text-align: right;">25.134513</td>
</tr>
<tr class="even">
<td style="text-align: left;">United States</td>
<td style="text-align: right;">2.236984e+13</td>
<td style="text-align: right;">30.95320</td>
<td style="text-align: right;">26.063274</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Uruguay</td>
<td style="text-align: right;">-1.047226e+11</td>
<td style="text-align: right;">25.07019</td>
<td style="text-align: right;">19.054479</td>
</tr>
<tr class="even">
<td style="text-align: left;">Uzbekistan</td>
<td style="text-align: right;">-8.067344e+10</td>
<td style="text-align: right;">25.34423</td>
<td style="text-align: right;">19.117010</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zambia</td>
<td style="text-align: right;">-1.500731e+11</td>
<td style="text-align: right;">24.04028</td>
<td style="text-align: right;">16.501188</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zimbabwe</td>
<td style="text-align: right;">-1.423176e+11</td>
<td style="text-align: right;">24.28520</td>
<td style="text-align: right;">16.172078</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_xlsx</span>(akai0,<span class="st">"akai0.xlsx"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(akai0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dalam grafik Residuals vs Fitted yang saya buat, saya melihat bahwa sebagian besar titik residual tersebar secara acak di sekitar garis horizontal nol. Ini memberikan indikasi awal bahwa model regresi yang saya gunakan memenuhi asumsi linearitas. Selain itu, varians residual tampaknya konstan, yang berarti asumsi homoskedastisitas juga cenderung terpenuhi.</p>
<p>Kemudian dilakukan Uji normalitas residual menggunakan Shapiro-Wilk test untuk mengevaluasi kualitas model regresi dan memastikan hasil analisis dapat dipercaya.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">resid</span>(log_akai0))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  resid(log_akai0)
W = 0.99177, p-value = 0.6339</code></pre>
</div>
</div>
<p>Berdasarkan hasil Shapiro-Wilk normality test yang saya lakukan, saya mendapatkan nilai W = 0.99177 dan p-value = 0.6339. Nilai W yang mendekati 1 menunjukkan bahwa data residual saya tidak jauh berbeda dari distribusi normal. Selain itu, dengan p-value sebesar 0.6339, yang lebih besar dari 0.05, saya tidak memiliki cukup bukti untuk menolak hipotesis nol bahwa data saya mengikuti distribusi normal. Dengan demikian, saya dapat menyimpulkan bahwa data residual saya mengikuti distribusi normal, dan asumsi normalitas dalam model regresi saya dapat diterima.</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Penelitian ini menerapkan metode regresi univariat atau Ordinary Least Square (OLS) dengan satu variabel independen. Penelitian ini bertujuan untuk mengkaji hubungan antara Ekspor teknologi tinggi dan GDP. Model yang digunakan dirancang secara khusus untuk merepresentasikan keterkaitan antara kedua variabel tersebut, dengan bentuk sebagai berikut:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah GDP dan <span class="math inline">\(x_t\)</span> adalah Ekspor teknologi tinggi.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Regresi yang telah dilakukan, menghasilkan data sebgai berikut:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>variable</th>
<th>Coefficients</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>16.77253</td>
</tr>
<tr class="even">
<td>X</td>
<td>0.43383</td>
</tr>
<tr class="odd">
<td>p-value</td>
<td>2.2e-16</td>
</tr>
<tr class="even">
<td>Multiple R-squared</td>
<td>0.7406</td>
</tr>
<tr class="odd">
<td>Adjusted R-squared</td>
<td>0.7386</td>
</tr>
</tbody>
</table>
<p>Sehingga didapatkan: <span class="math display">\[y_{t}=\ (16.77253) + \ (0.43383)x+\mu_t\]</span></p>
<p>Setelah melakukan transformasi logaritmik pada variabel Y (GDP) dan X (Ekspor Teknologi Tinggi), model yang dihasilkan menunjukkan Koefisien sebesar 0.43383 yang artinya setiap kenaikan 1% pada ekspor teknologi tinggi (X) akan meningkatkan GDP (Y) sebesar 0.43383%. Ini mengindikasikan adanya hubungan positif yang signifikan antara kedua variabel.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(log_Y <span class="sc">~</span> log_X,<span class="at">data=</span>akai0)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log_Y ~ log_X, data = akai0)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.5777 -0.7914 -0.0435  0.7127  3.0292 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 16.77253    0.44801   37.44   &lt;2e-16 ***
log_X        0.43383    0.02252   19.27   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.132 on 130 degrees of freedom
Multiple R-squared:  0.7406,    Adjusted R-squared:  0.7386 
F-statistic: 371.2 on 1 and 130 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Koefisien untuk log_X sebesar 0.43383 menunjukkan bahwa setiap kenaikan satu unit pada log_X akan meningkatkan log_Y sebesar 0.43383, dan hasil ini sangat signifikan secara statistik (p-value &lt; 2e-16). Nilai R-squared sebesar 0.7406 menunjukkan bahwa sekitar 74% variasi dalam log_Y dapat dijelaskan oleh log_X, yang menunjukkan kekuatan model dalam menggambarkan hubungan tersebut. Adjusted R-squared yang sedikit lebih rendah (0.7386) juga mendukung bahwa model ini tetap baik meskipun hanya melibatkan satu variabel. Selain itu, F-statistic sebesar 371.2 dengan p-value yang sangat kecil (&lt; 2.2e-16) menunjukkan bahwa model secara keseluruhan signifikan.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Penelitian ini menganalisis pengaruh ekspor teknologi tinggi terhadap GDP di 135 negara pada tahun 2022, dengan tujuan untuk memahami kontribusi ekspor teknologi tinggi terhadap pertumbuhan ekonomi dan faktor-faktor yang mempengaruhinya. Berdasarkan hasil regresi yang dilakukan, ditemukan bahwa terdapat hubungan positif yang signifikan antara ekspor teknologi tinggi (X) dan GDP (Y). Setiap peningkatan 1% dalam ekspor teknologi tinggi diperkirakan akan meningkatkan GDP sebesar 0.43383%. Model regresi yang digunakan mampu menjelaskan sekitar 74% variasi dalam GDP, menunjukkan kekuatan hubungan antara kedua variabel tersebut.</p>
<p>Namun, analisis residual menunjukkan adanya potensi masalah heteroskedastisitas, yang berarti varians residual tidak konstan di seluruh rentang data, terutama pada GDP yang lebih tinggi. Untuk mengatasi hal ini, dilakukan transformasi logaritmik pada data, yang menghasilkan model yang lebih baik dengan asumsi normalitas dan homoskedastisitas yang terpenuhi. Hasil uji Shapiro-Wilk menunjukkan bahwa data residual mengikuti distribusi normal, yang mengindikasikan kualitas model yang baik. Penelitian ini menyimpulkan bahwa ekspor teknologi tinggi memiliki dampak yang signifikan terhadap pertumbuhan ekonomi, dengan hubungan yang dapat dijelaskan melalui model regresi logaritmik.</p>
<p>Secara teoritis, ekspor teknologi tinggi memiliki dampak signifikan terhadap pertumbuhan ekonomi karena beberapa alasan yang mendalam. Pertama, ekspor teknologi tinggi dapat meningkatkan daya saing suatu negara di pasar global. Produk teknologi tinggi, seperti elektronik, bioteknologi, dan perangkat keras canggih, sering kali memiliki nilai tambah yang lebih tinggi dibandingkan dengan produk tradisional. Ini berarti bahwa ekspor produk semacam itu dapat meningkatkan pendapatan negara melalui peningkatan nilai ekspor, yang secara langsung berkontribusi terhadap GDP.</p>
<p>Kedua, sektor teknologi tinggi sering kali memerlukan investasi besar dalam penelitian dan pengembangan (R&amp;D), yang mendorong inovasi. Inovasi ini tidak hanya meningkatkan kualitas dan efisiensi produk tetapi juga dapat menciptakan sektor-sektor industri baru yang lebih produktif. Peningkatan produktivitas ini mendorong pertumbuhan ekonomi secara keseluruhan, karena sektor-sektor ekonomi yang lebih efisien dapat beroperasi dengan biaya yang lebih rendah, sambil menghasilkan lebih banyak produk atau jasa.</p>
<p>Ketiga, ekspor teknologi tinggi juga berperan dalam menciptakan lapangan kerja yang lebih berkualitas. Industri berbasis teknologi canggih sering kali membutuhkan tenaga kerja dengan keterampilan tinggi, yang mendorong peningkatan kualitas tenaga kerja di suatu negara. Peningkatan kualitas sumber daya manusia ini akan berkontribusi pada penguatan sektor-sektor ekonomi lainnya dan secara tidak langsung meningkatkan pertumbuhan ekonomi.</p>
<p>Keempat, ekspor teknologi tinggi dapat memperkuat posisi negara dalam rantai pasokan global. Negara yang mampu memproduksi dan mengekspor produk-produk teknologi tinggi akan lebih mudah mengakses pasar internasional, yang memberikan peluang lebih besar untuk pertumbuhan ekonomi. Hal ini terkait dengan teori perdagangan internasional yang menunjukkan bahwa negara yang terlibat dalam perdagangan barang-barang dengan nilai tambah tinggi akan merasakan manfaat pertumbuhan yang lebih cepat.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>https://id.tradingeconomics.com</p>
<p>https://www.bps.go.id/id BPS</p>
<p>https://www.worldbank.org/ext/en/home world bank</p>
<p>• OECD. (2021). The Digital Economy Outlook 2021. Paris: OECD Publishing.</p>
<p>• Krugman, P., &amp; Obstfeld, M. (2018). International Economics: Theory and Policy. Pearson.</p>
<p>• Lall, S. (2000). “The Technological Structure of Developing Country Exports.” Oxford Development Studies, 28(3), 337-354.</p>
<p>• Lee, K., &amp; Malerba, F. (2018). “Innovation and the Global Economy.” Research Policy, 47(9), 1768-1780.</p>
<p>• Banga, R. (2015). “Impact of High-Tech Exports on Economic Growth: Evidence from Developing Countries.” Journal of Economic Studies, 42(5), 925-945.</p>
<p>• Xu, B., &amp; Wang, Z. (2020). “Education, Technology, and Economic Growth: A Global Perspective.” The World Economy, 43(2), 458-482..</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>